#!/bin/bash

ryd_per_ev=0.0734986176
system=hBN
base_dir=supercell_extrapolation_calculations
functional=pbe
vdw_corr=none
ecp=hgh
ecut_ev=700
Nk=3

if [ ! -d "${base_dir}" ]; then
	mkdir $base_dir
fi

for Ns in 1 2 3 4 5 6 7 8 9
	do
		calc_dir=${system}_${functional}_vdw_${vdw_corr}_${ecp}_ecut_${ecut_ev}_Nk_${Nk}_Ns_${Ns}
		if [ ! -d "${base_dir}/${calc_dir}" ]; then
			mkdir ${base_dir}/${calc_dir}
		fi
		cp ../quantum_espresso_example/pw.x ../pseudopotentials/*${ecp}*.UPF ${base_dir}/${calc_dir}
		ecut_ryd=$(bc<<<${ecut_ev}*${ryd_per_ev})
		python generate_scf_input_file.py $base_dir $calc_dir $system $functional $vdw_corr $ecut_ryd $Nk $Ns
		python generate_quantum_espresso_submission.py $base_dir $calc_dir
		submission_script=${calc_dir}.sh
		sbatch $submission_script
	done
